services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vanity_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - vanity_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: >
      sh -c "chown -R www-data:www-data storage bootstrap/cache &&
             chmod -R 775 storage bootstrap/cache &&
             php-fpm"

  webserver:
    image: nginx:alpine
    container_name: vanity_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - vanity_network

  db:
    image: mysql:8.0
    container_name: vanity_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vanity
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vanity_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - vanity_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vanity_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - vanity_network

networks:
  vanity_network:
    driver: bridge

volumes:
  dbdata:
